package filter

import (
	"fmt"
	"strings"
	"testing"
	"time"

	"github.com/codyconfer/mino/internal/signals"
)

var benchRepos = []string{
	"acme/tools",
	"acme/signals-core",
	"acme/deck",
	"acme/infra-terraform",
	"acme/observability-agent",
}

var benchAuthors = []string{"cody", "alice", "bhargav", "mira", "sven", "quinn"}

var benchPassRules = []Rule{
	{Field: "title", Exclude: `(?i)\b(do not merge|hold off|abandoned)\b`},
	{Field: "body", Include: `(?i)(signals|poller|backoff|cache|flight)`},
	{Field: "meta.author", Exclude: `(?i)^(dependabot|renovate|github-actions)(\[bot\])?$`},
	{Field: "subtitle", Exclude: `(?i)\barchived\b`},
	{Field: "meta.labels", Include: `(?i)(area/[a-z-]+|bug|perf|regression)`},
	{Field: "body", Exclude: `(?i)this pull request was generated by a bot`},
	{Field: "meta.assignees", Include: `\S`},
	{Field: "meta.last_comment_by", Exclude: `(?i)^(codecov|sonarcloud)(\[bot\])?$`},
}

var benchSelectRule = Rule{Field: "meta.state", Include: `^(open|in review)$`}

func benchFilters(filters, rulesEach int) []Compiled {
	specs := make([]Filter, 0, filters)
	for f := range filters {
		rules := make([]Rule, 0, rulesEach)
		for r := range rulesEach - 1 {
			rules = append(rules, benchPassRules[(f*rulesEach+r)%len(benchPassRules)])
		}
		rules = append(rules, benchSelectRule)
		specs = append(specs, Filter{Name: fmt.Sprintf("bench-%d", f), Rules: rules})
	}
	compiled, err := CompileAll(specs)
	if err != nil {
		panic(err)
	}
	return compiled
}

func benchBody(i int) string {
	var b strings.Builder
	b.Grow(1024)
	fmt.Fprintf(&b, "## Summary\n\nThe %s poller re-armed its backoff timer on every tick, so a stale\n", benchRepos[i%len(benchRepos)])
	b.WriteString("cache entry could be refetched dozens of times inside one flight. This clamps\n")
	b.WriteString("the interval and reuses the existing timer instead of allocating a new one.\n\n")
	b.WriteString("### Changes\n\n")
	b.WriteString("- clamp `backoff` to `[1s, 5m]` and jitter it by up to 10%\n")
	b.WriteString("- reuse the idle timer rather than allocating per operation\n")
	b.WriteString("- record the signals cache hit ratio in the audit journal\n")
	b.WriteString("- drop the redundant directory fsync from the collection writer\n\n")
	b.WriteString("### Testing\n\n")
	fmt.Fprintf(&b, "```\ngo test ./internal/... -run Poller -count=%d\n```\n\n", i%5+1)
	b.WriteString("Verified against a recorded flight of 8 queries; the refetch count drops from\n")
	fmt.Fprintf(&b, "%d to %d and wall clock from 1.4s to 180ms.\n\n", 40+i%17, i%3+1)
	b.WriteString("Closes #")
	fmt.Fprintf(&b, "%d\n", 1200+i)
	return b.String()
}

func benchItems(n int) []signals.Item {
	base := time.Now()
	items := make([]signals.Item, 0, n)
	for i := range n {
		repo := benchRepos[i%len(benchRepos)]
		state := "open"
		switch i % 5 {
		case 3:
			state = "closed"
		case 4:
			state = "merged"
		}
		ts := base.Add(-time.Duration(i%71+1) * time.Hour)
		items = append(items, signals.Item{
			Kind:      "pr",
			Title:     fmt.Sprintf("Clamp the %s poller backoff so a stale cache entry is not refetched (#%d)", repo, 400+i),
			Subtitle:  fmt.Sprintf("%s · In Review · %d approvals · %d files", repo, i%3, 3+i%9),
			Body:      benchBody(i),
			URL:       fmt.Sprintf("https://github.com/%s/pull/%d", repo, 400+i),
			Timestamp: ts,
			Meta: map[string]string{
				"author":            benchAuthors[i%len(benchAuthors)],
				"state":             state,
				"status":            "In Review",
				"labels":            "bug, area/signals, perf",
				"assignees":         benchAuthors[(i+2)%len(benchAuthors)],
				"draft":             fmt.Sprint(i%11 == 0),
				"last_comment_by":   benchAuthors[(i+1)%len(benchAuthors)],
				"last_comment_at":   ts.Add(30 * time.Minute).Format(time.RFC3339),
				"last_comment_team": fmt.Sprint(i%2 == 0),
			},
		})
	}
	return items
}

var benchKept []signals.Item

func BenchmarkApplyAll(b *testing.B) {
	prev := ExternalEngine
	ExternalEngine = nil
	b.Cleanup(func() { ExternalEngine = prev })

	shapes := []struct {
		filters   int
		rulesEach int
	}{
		{1, 1},
		{1, 4},
		{1, 16},
		{3, 4},
	}
	for _, n := range []int{50, 200, 1000} {
		items := benchItems(n)
		for _, s := range shapes {
			compiled := benchFilters(s.filters, s.rulesEach)
			name := fmt.Sprintf("items=%d/filters=%d/rules_each=%d", n, s.filters, s.rulesEach)
			b.Run(name, func(b *testing.B) {
				b.ReportAllocs()
				for b.Loop() {
					benchKept = ApplyAll(compiled, items)
				}
				if len(benchKept) == 0 {
					b.Fatal("filter kept nothing; fixture is degenerate")
				}
			})
		}
	}
}

func TestBenchApplyAllFixtureKeepsRealisticFraction(t *testing.T) {
	items := benchItems(200)
	kept := ApplyAll(benchFilters(1, 4), items)
	if len(kept) != 120 {
		t.Fatalf("kept %d of %d items; fixture should keep 120 so the benchmark is not degenerate", len(kept), len(items))
	}
	for _, it := range items[:1] {
		if len(it.Body) < 600 {
			t.Fatalf("fixture body is %d bytes; want a realistic multi-hundred-byte body", len(it.Body))
		}
	}
}
