package filter

import (
	"fmt"
	"testing"

	"github.com/codyconfer/mino/internal/signals"
)

// diffPatterns covers every regexp metacharacter, escaped-literal forms, and
// the plain literals the fast path is meant to catch.
var diffPatterns = []string{
	// plain literals (expected to take the fast path)
	"incident", "deploy ok", "a", " ", "-", "#", "&", "~", "/", "%", "!", "=",
	":", ",", "'", "\"", "<", ">", "@", "café", "日本", "a\nb", "a\tb", "\x00",
	"Incident", "INCIDENT",
	// bare metacharacters
	".", "a.c", "a*", "a+", "a?", "a|b", "(a)", "[a]", "[^a]", "a{2}", "a{2,}",
	"^abc", "abc$", "^abc$", "^", "$", "^$",
	// escaped-literal forms
	`a\.c`, `\.`, `\*`, `\+`, `\?`, `\|`, `\(`, `\)`, `\[`, `\]`, `\{`, `\}`,
	`\^`, `\$`, `\\`, `a\\b`,
	// classes, flags, anchors, groups
	`\d`, `\w`, `\s`, `\S`, `\b`, `\Babc`, `\Aabc\z`, "(?i)abc", "(?i)INCIDENT",
	"(?s).", "(?m)^a", "(?:ab)+", "a(?:b|c)d", "[[:alpha:]]", `\p{L}`,
	"(?i)bot$", "(?i)(signals|poller|backoff)", `\b(do not merge|hold off)\b`,
	// U+FFFD: regexp also matches invalid input bytes with it
	"�", "x�y",
}

// diffInputs includes invalid UTF-8 and metacharacter-bearing text.
var diffInputs = []string{
	"", "a", "abc", "ABC", "Incident opened", "incident", "sev2 incident",
	"deploy ok", "all green", "a.c", "axc", "aac", "ab", "ac", "abd", "a|b",
	"(a)", "[a]", "{2}", "^abc$", `a\b`, `a\\b`, "a*", "a+", "a?", "$", "^",
	"café", "日本", "a\nb", "a\tb", "\x00", " ", "-", "#", "&", "~", "/", "%",
	"caf\xe9", "a\xffb", "\xe9", "x�y", "�", "do not merge now",
	"signals poller backoff", "dependabot", "a-bot", "long body with signals " +
		"and a poller and some backoff text that is realistic in length",
}

// regexOnly strips the literal fast path so both paths can be compared.
func regexOnly(c Compiled) Compiled {
	rules := make([]compiledRule, len(c.rules))
	for i, r := range c.rules {
		rules[i] = compiledRule{field: r.field, include: r.include, exclude: r.exclude}
	}
	return Compiled{Name: c.Name, rules: rules}
}

// TestLiteralFastPathMatchesRegexp is the differential test: for every pattern
// and input, the fast path must agree with the pure regexp path exactly.
func TestLiteralFastPathMatchesRegexp(t *testing.T) {
	for _, pat := range diffPatterns {
		for _, side := range []string{"include", "exclude"} {
			rule := Rule{Field: "body"}
			if side == "include" {
				rule.Include = pat
			} else {
				rule.Exclude = pat
			}
			fast, err := Compile(Filter{Name: "diff", Rules: []Rule{rule}})
			if err != nil {
				t.Fatalf("Compile(%s=%q): %v", side, pat, err)
			}
			slow := regexOnly(fast)
			for _, in := range diffInputs {
				it := signals.Item{Body: in}
				got, want := fast.keeps(it), slow.keeps(it)
				if got != want {
					t.Errorf("%s=%q input=%q: fast path kept=%v, regexp path kept=%v (lit=%q)",
						side, pat, in, got, want, literalOf(pat))
				}
			}
		}
	}
}

// benchLiteralRules mirrors benchPassRules but as the plain literals that real
// filters mostly use, so the fast path is exercised.
var benchLiteralRules = []Rule{
	{Field: "title", Exclude: "do not merge"},
	{Field: "body", Include: "poller"},
	{Field: "meta.author", Exclude: "dependabot"},
	{Field: "subtitle", Exclude: "archived"},
	{Field: "meta.labels", Include: "perf"},
	{Field: "body", Exclude: "this pull request was generated by a bot"},
	{Field: "meta.assignees", Include: "a"},
	{Field: "meta.last_comment_by", Exclude: "codecov"},
}

// BenchmarkApplyAllLiteral compares the literal fast path against the regexp
// path on identical rules, in one binary, so the delta is not machine noise.
func BenchmarkApplyAllLiteral(b *testing.B) {
	prev := ExternalEngine
	ExternalEngine = nil
	b.Cleanup(func() { ExternalEngine = prev })

	for _, n := range []int{200, 1000} {
		items := benchItems(n)
		for _, rulesEach := range []int{4, 16} {
			rules := make([]Rule, 0, rulesEach)
			for r := range rulesEach {
				rules = append(rules, benchLiteralRules[r%len(benchLiteralRules)])
			}
			compiled, err := CompileAll([]Filter{{Name: "lit", Rules: rules}})
			if err != nil {
				b.Fatal(err)
			}
			slow := []Compiled{regexOnly(compiled[0])}
			for _, v := range []struct {
				name string
				c    []Compiled
			}{{"fast", compiled}, {"regexp", slow}} {
				name := fmt.Sprintf("items=%d/rules_each=%d/%s", n, rulesEach, v.name)
				b.Run(name, func(b *testing.B) {
					b.ReportAllocs()
					for b.Loop() {
						benchKept = ApplyAll(v.c, items)
					}
					if len(benchKept) == 0 {
						b.Fatal("filter kept nothing; fixture is degenerate")
					}
				})
			}
		}
	}
}

// TestLiteralDetection pins which patterns are allowed onto the fast path.
func TestLiteralDetection(t *testing.T) {
	tests := []struct {
		pat  string
		want string
	}{
		{"incident", "incident"},
		{"deploy ok", "deploy ok"},
		{"Incident", "Incident"},
		{"café", "café"},
		{"a\nb", "a\nb"},
		{"\x00", "\x00"},
		{"-", "-"},
		{"", ""},
		// every metacharacter must fall back to the regexp path
		{".", ""}, {"a.c", ""}, {"a*", ""}, {"a+", ""}, {"a?", ""}, {"a|b", ""},
		{"(a)", ""}, {"[a]", ""}, {"a{2}", ""}, {"^abc", ""}, {"abc$", ""},
		{"^abc$", ""}, {`a\.c`, ""}, {`\\`, ""}, {"(?i)abc", ""}, {`\d`, ""},
		{`\Aabc\z`, ""}, {`\babc`, ""},
		// U+FFFD also matches invalid input bytes under regexp
		{"�", ""}, {"x�y", ""},
	}
	for _, tt := range tests {
		if got := literalOf(tt.pat); got != tt.want {
			t.Errorf("literalOf(%q) = %q, want %q", tt.pat, got, tt.want)
		}
	}
}

// TestLiteralFastPathIsCaseSensitive guards against the fast path folding case.
func TestLiteralFastPathIsCaseSensitive(t *testing.T) {
	c := mustCompile(t, Filter{Name: "cs", Rules: []Rule{{Field: "title", Include: "Incident"}}})
	if got := titles(c.Apply(items())); len(got) != 1 || got[0] != "Incident opened" {
		t.Fatalf("got %v, want [Incident opened]", got)
	}
	lower := mustCompile(t, Filter{Name: "cs", Rules: []Rule{{Field: "title", Include: "incident"}}})
	if got := lower.Apply(items()); len(got) != 0 {
		t.Fatalf("lowercase literal must not match %v", titles(got))
	}
}

// TestLiteralFastPathIsUnanchored keeps substring semantics, not full match.
func TestLiteralFastPathIsUnanchored(t *testing.T) {
	c := mustCompile(t, Filter{Name: "sub", Rules: []Rule{{Field: "title", Include: "cident op"}}})
	if got := titles(c.Apply(items())); len(got) != 1 || got[0] != "Incident opened" {
		t.Fatalf("got %v, want [Incident opened]", got)
	}
}

// TestUTF8ReplacementCharNotFastPathed pins the one case where strings.Contains
// and regexp genuinely disagree: U+FFFD matches invalid bytes in the input.
func TestUTF8ReplacementCharNotFastPathed(t *testing.T) {
	c := mustCompile(t, Filter{Name: "bad", Rules: []Rule{{Field: "body", Include: "�"}}})
	if c.rules[0].includeLit != "" {
		t.Fatal("U+FFFD must not take the literal fast path")
	}
	it := signals.Item{Body: "caf\xe9"}
	if !c.keeps(it) {
		t.Fatal("regexp path must match an invalid byte against U+FFFD")
	}
}
